# Generated by Django 4.1.5 on 2023-01-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='pl',
        ),
    ]
